### ISSUE TITLE
Training the model just results in a small .h5 file

### ISSUE THREAD

**Issue by MorphToru** [fritzlabs/fritz-image-segmentation#4]
Following your amazing instruction, just choosing ‘person’ category and and runnning. Getting following error

Dimension 0 in both shapes must be equal, but are 3 and 8. Shapes are [3, 3, 3, 32] and [8, 3, 3, 3]. For ‘Assign_382’ 

Any advice would be appreciated.

Toru

**Comment by jamesonthecrow** [comment]
Do you mind posting the full error message so I can take a look at the line of code that is breaking along with the exact input command you’re running. Thanks!

**Comment by MorphToru** [comment]
Hi James,

Thanks so much for the quick response. We figured out internally. We trained with alpha=0.25, but when we tried to build the model with and load our weights (human_icnet_768x768_025.mlmodel), the alpha was not specified, so the default of 1 was used. Once I added it in as a parameter below, the model load and also I could export it to coreml using the command
python convert_to_coreml.py --alpha 0.25 human_icnet_768x768_025.h5 human_icnet_768x768_025.mlmodel

Works
icnet_human = ICNetModelFactory.build(
    img_size=768,
    n_classes=2,
    alpha=0.25,
    weights_path='examples/human_icnet_768x768_025.h5',
    train=False
)

Error
icnet_human = ICNetModelFactory.build(
    img_size=768,
    n_classes=2,
    weights_path='examples/human_icnet_768x768_025.h5',
    train=False
)
InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 8. Shapes are [3,3,3,32] and [8,3,3,3]. for 'Assign_3041' (op: 'Assign') with input shapes: [3,3,3,32], [8,3,3,3].

Trying to improve it with just the “Person” as a category but seems to perform not too well. Will maybe ask once we get some training and still can’t get it to work. 

Thanks again.

Best,
Toru

**Comment by jamesonthecrow** [comment]
Glad you got things to work. Things are a bit better if you choose a larger alpha, but I've noticed the model struggles with people in non-standing positions. But for street scenes, thing seem to work fairly well. That said, I think more data would improve things. The I'd love to see someone add support for additional datasets like CityScapes. Let us know if you need any more help.

![image](https://user-images.githubusercontent.com/337862/46035268-a9d77380-c0d0-11e8-9958-2ed4f787bc0a.png)
